# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2bfa8fa99f314fa560481e3d1fa3912fb6d766673872d72ae4e158b16576bffa7e5ece66b02ca4ae789ca881561db86397eebaf8337ad03e12231424a2723f0

test:
  secret_key_base: eed18041729bb2e71b469bf7d3f6c2f830918b6167b5df7d65cf3f5bc626ddd5d369f41d7d0fefaecb08bf2d17783cbc89406ed24abfbd8059c6b85109984040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
